feat: pre commit hook test

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,13 +1,10 @@
-#!/bin/sh
-
-echo "Running git pre-commit hook "
-
+#!/bin/bash
+echo "Running git pre-commit hook"
 ./gradlew ktlintCheck
-
 ktlintCheckStatus=$?
-
-if [[ktlintCheckStatus -ne 0]] then
-  exit 1
+# return 1 if check fails
+if [[ $ktlintCheckStatus -ne 0 ]]; then
+     exit 1
 else
-  exit 0
+     exit 0
 fi
